[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

# Hides the hamburger menu (top right corner)
hideMenu = true

# Hides the Streamlit watermark (bottom right corner)
hideStreamlitMark = true
